name: Push test
run-name: ${{ github.actor }} is testing out the push test
on:
  push:
    branches:
      - main
    paths:
      - 'yml/*.yml'
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    environment: DeployDatabase
    steps:
      - name: echo new test
        run: echo "test 2"
